<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>certbot on bramp.net</title>
    <link>https://blog.bramp.net</link>
    <description>Recent content in certbot on bramp.net</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en_GB</language>
    <lastBuildDate>Sat, 26 May 2018 11:28:44 -0700</lastBuildDate>
    <atom:link href="https://blog.bramp.net/tags/certbot/" rel="self" type="application/rss+xml" />
    
    <item>
      <title>Certbot: Unexpected Error</title>
      <link>https://blog.bramp.net/post/2018/05/26/certbot-unexpected-error/</link>
      <pubDate>Sat, 26 May 2018 11:28:44 -0700</pubDate>
      
      <guid>https://blog.bramp.net/post/2018/05/26/certbot-unexpected-error/</guid>
      <description>&lt;p&gt;I got a &lt;a href=&#34;https://letsencrypt.org/docs/expiration-emails/&#34;&gt;nice warning email&lt;/a&gt; from &lt;a href=&#34;https://letsencrypt.org/&#34;&gt;Let&amp;rsquo;s Encrypt&lt;/a&gt; that my cert was going to expire soon, and hadn&amp;rsquo;t been renewed. I found in  &lt;code&gt;/var/log/letsencrypt/letsencrypt.log&lt;/code&gt; the following error:&lt;/p&gt;
&lt;pre&gt;&lt;code&gt;Renewal configuration file /etc/letsencrypt/renewal/mydomain.bramp.net.conf (cert: mydomain.bramp.net) produced an unexpected error: &#39;Namespace&#39; object has no attribute &#39;dns_cloudflare_credentials&#39;. Skipping.
&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;I manually ran certbot in dry-run mode and it worked fine:&lt;/p&gt;
&lt;div class=&#34;highlight&#34;&gt;&lt;pre class=&#34;chroma&#34;&gt;&lt;code class=&#34;language-shell&#34; data-lang=&#34;shell&#34;&gt;$ sudo certbot renew --dry-run
&lt;/code&gt;&lt;/pre&gt;&lt;/div&gt;&lt;p&gt;So this error only occurs when certbot is running as a cron job. Looking at &lt;code&gt;/etc/cron.d/certbot&lt;/code&gt; I see the user runs as root, so I tried the &lt;code&gt;certbot renew --dry-run&lt;/code&gt; again, but this time as the root user:&lt;/p&gt;
&lt;div class=&#34;highlight&#34;&gt;&lt;pre class=&#34;chroma&#34;&gt;&lt;code class=&#34;language-shell&#34; data-lang=&#34;shell&#34;&gt;$ sudo su
root@:~$ sudo certbot renew --dry-run
&lt;/code&gt;&lt;/pre&gt;&lt;/div&gt;&lt;p&gt;and bam, the same error. This error somehow related to the &lt;a href=&#34;https://certbot-dns-cloudflare.readthedocs.io/en/latest/&#34;&gt;certbot-dns-cloudflare plugin&lt;/a&gt;, which proves the ownership of the domain with a &lt;a href=&#34;https://acme-python.readthedocs.io/en/latest/api/challenges.html#acme.challenges.DNS01&#34;&gt;DNS01 challenge&lt;/a&gt; via Cloudflare&amp;rsquo;s DNS. I use this form of challenge, because the domain in question is internal and not available on the Internet.&lt;/p&gt;
&lt;p&gt;I had forgotten how I installed the plugin, but searching Google, it seems to be via &lt;code&gt;pip3&lt;/code&gt;. Clearly something was different between my root and normal user w/ sudo environments. So I did the following&lt;/p&gt;
&lt;div class=&#34;highlight&#34;&gt;&lt;pre class=&#34;chroma&#34;&gt;&lt;code class=&#34;language-shell&#34; data-lang=&#34;shell&#34;&gt;$ sudo pip3 list &lt;span class=&#34;p&#34;&gt;|&lt;/span&gt; grep certbot
certbot &lt;span class=&#34;o&#34;&gt;(&lt;/span&gt;0.23.0&lt;span class=&#34;o&#34;&gt;)&lt;/span&gt;
certbot-apache &lt;span class=&#34;o&#34;&gt;(&lt;/span&gt;0.23.0&lt;span class=&#34;o&#34;&gt;)&lt;/span&gt;
certbot-dns-cloudflare &lt;span class=&#34;o&#34;&gt;(&lt;/span&gt;0.24.0&lt;span class=&#34;o&#34;&gt;)&lt;/span&gt;

$ sudo su
root@:~$ pip3 list &lt;span class=&#34;p&#34;&gt;|&lt;/span&gt; grep certbot
certbot &lt;span class=&#34;o&#34;&gt;(&lt;/span&gt;0.23.0&lt;span class=&#34;o&#34;&gt;)&lt;/span&gt;
certbot-apache &lt;span class=&#34;o&#34;&gt;(&lt;/span&gt;0.23.0&lt;span class=&#34;o&#34;&gt;)&lt;/span&gt;
&lt;/code&gt;&lt;/pre&gt;&lt;/div&gt;&lt;p&gt;Aha, no certbot-dns-cloudflare when running as root. Clearly I hadn&amp;rsquo;t installed this correctly. Running &lt;code&gt;pip3 install certbot-dns-cloudflare&lt;/code&gt; as root fixed the problem, and voila, certbot correctly fetches new certs via a regular cron.&lt;/p&gt;
</description>
    </item>
    
  </channel>
</rss>